import './globals.css';

import { ReactElement, ReactNode } from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { AuthProvider } from '@/contexts/auth-context';

const inter = localFont({
  src: [
    {
      path: './fonts/InterVariable.woff2',
      style: 'normal',
    },
    {
      path: './fonts/InterVariable-Italic.woff2',
      style: 'italic',
    },
  ],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactElement {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
